import type { Metadata } from 'next'
import './globals.css'

import { GeistSans } from 'geist/font';

import { cn } from '@/lib/utils'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  const classNmaes = `
    ${cn("min-h-screen bg-background font-sans antialiased")}
    ${GeistSans.className}
  `;

  return (
    <html lang="ko">
      <body
        className={classNmaes}
      >
        {children}
      </body>
    </html>
  )
}
