import type { Metadata } from "next";
import { GeistSans } from "geist/font";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/wrapper/ThemeProvider";
import MainLayoutWrapper from "@/components/wrapper/MainLayoutWrapper";
import AuthProvider from "@/components/wrapper/AuthProvider";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const classNmaes = `
    ${cn("h-full bg-background font-sans antialiased")}
    ${GeistSans.className}
  `;

  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={classNmaes}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider accessToken={session?.access_token}>
            <MainLayoutWrapper>{children}</MainLayoutWrapper>
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
